#!/usr/bin/env python3.10
import argparse
import json
import random
import sqlite3
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="LearnWords is a programm to help you learn words easy!"
    )
    subparsers = parser.add_subparsers()
    parser.set_defaults(func=greetings)

    parser_add = subparsers.add_parser("add")
    parser_add.add_argument("text", type=str)
    parser_add.add_argument("translation", type=str)
    parser_add.set_defaults(func=add)

    parser_learn = subparsers.add_parser("learn")
    parser_learn.set_defaults(func=learn)

    args = parser.parse_args()
    args.func(args)


def add(args):
    connection = sqlite3.connect("dictionary.sqlite3")
    cursor = connection.cursor()
    cursor.execute(
        "INSERT INTO dictionary (primary_text, translation) VALUES(?, ?)",
        [args.text, args.translation],
    )
    connection.commit()
    print(f"Translation is added!")


def learn(args):
    print("You are about to learn words!")


def greetings(args):
    print("WELCOME to LearnWords!\n" "To read help use -h or --help options\n")


if __name__ == "__main__":
    main()
